name: Integracion Continua en ramas de Features

on:
  push:
    branches:
      - 'feature/**'

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test

      - name: Enviar Retroalimentación a Slack (Éxito)
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "✅ Los Tests para la rama ${{ github.ref_name }} han PASADO exitosamente.",
              "username": "GitHub Actions CI",
              "channel": "#general-parcial-ic"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_1 }}

      - name: Enviar Retroalimentación a Slack (Fallo)
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "❌ Los Tests para la rama ${{ github.ref_name }} han FALLADO. Ver logs de GitHub Actions.",
              "username": "GitHub Actions CI",
              "channel": "#general-parcial-ic"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_1 }}