name: Integracion Continua en ramas de Features

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Enviar Retroalimentación a Slack (Éxito)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        with: 
          status: success
          message: "✅ Build y Tests para la rama ${{ github.ref_name }} han PASADO exitosamente."
          channel: '#general-parcial-ic'
          username: 'GitHub Actions CI'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Enviar Retroalimentación a Slack (Fallo)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: failure
          message: "❌ Build y Tests para la rama ${{ github.ref_name }} han FALLADO. Ver logs de GitHub Actions."
          channel: '#general-parcial-ic'
          username: 'GitHub Actions CI'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}