name: Integracion Continua en ramas de Features

on:
  push:
    branches:
      - 'feature/**'

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test

      - name: Notificacion Slack
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_1 }}
          SLACK_CHANNEL: notificaciones-features
          SLACK_COLOR: ${{ job.status }}
          MSG_MINIMAL: actions url

          SLACK_MESSAGE: |
            *${{ job.status == 'success' && ':white_check_mark: Tests pasaron exitosamente' || ':x: Tests fallaron' }} en `${{ github.ref_name }}`*

            *Autor:* `${{ github.actor }}`
            *Commit:* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>
            *Workflow:* `${{ github.workflow }}`
            *Ver ejecución:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Ver en GitHub Actions>

          SLACK_MESSAGE_ON_SUCCESS: ''
          SLACK_MESSAGE_ON_FAILURE: ''
          SLACK_MESSAGE_ON_CANCEL: 'Job cancelado :warning:'