name: Validacion de PR a main

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test

      - name: Enviar Notificación a Slack (Nueva solicitud de PR)
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "*Nueva solicitud de Pull Request*\n\n*Autor:* ${{ github.actor }}\n*Desde:* `${{ github.head_ref }}` → `${{ github.base_ref }}`\n*Repositorio:* ${{ github.repository }}\n*Ver PR:* <${{ github.event.pull_request.html_url }}|Click aquí para verlo>",
              "username": "GitHub Actions CD",
              "channel": "#notificaciones-pr"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_2 }}